steps:
  # Bygg Docker-image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--platform=linux/amd64', '-t', 'gcr.io/spk-hytta/hyttebooking-backend:$COMMIT_SHA', '-f', 'backend/hyttebooker/Dockerfile', '.']

      # Push image til Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/spk-hytta/hyttebooking-backend:$COMMIT_SHA']

  # Deploy til Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'hyttebooking-backend',
           '--image', 'gcr.io/spk-hytta/hyttebooking-backend:$COMMIT_SHA',
           '--region', 'europe-west1',
           '--platform', 'managed',
           '--allow-unauthenticated']

# Løse logging-konflikten
options:
  logging: CLOUD_LOGGING_ONLY