name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  APP_NAME: 'hyttebooker-app-backend'
  PROJECT_ID: 'spk-hytta'
  PROJECT_NMR: 508319635743
  REGION: 'europe-west1'
  REGISTRY_NAME: 'run-image'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - id: 'Checkout'
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{env.PROJECT_NMR}}/locations/global/workloadIdentityPools/github-actions/providers/github-provider'
          service_account: 'github-wif@${{env.PROJECT_ID}}.iam.gserviceaccount.com'
          project_id: ${{env.PROJECT_ID}}

      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './src'
          destination: '${{env.PROJECT_ID}}-static-content'
          parent: false

      - id: 'build-api-image'
        run: |-
          gcloud builds submit ./backend/hyttebooker \
          --tag $REGION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$APP_NAME:$GITHUB_SHA \
          --service-account=projects/$PROJECT_ID/serviceAccounts/cloudbuild-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --default-buckets-behavior=REGIONAL_USER_OWNED_BUCKET

      - id: 'deploy-api-image'
        run: |-
          gcloud run deploy $APP_NAME \
          --region $REGION \
          --image $REGION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$APP_NAME:$GITHUB_SHA \
          --service-account=cloudrun-sa@$PROJECT_ID.iam.gserviceaccount.com

