name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true

      - name: Write Firebase Admin SDK key to file
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.FIREBASE_ADMIN_SDK_JSON }}" > src/main/resources/firebase-adminsdk.json

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
          docker build --platform linux/amd64 -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spkhytta/spkhytta .
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spkhytta/spkhytta

      - name: Get secrets
        run: |
          echo "DB_URL=$(gcloud secrets versions access latest --secret=DB_URL)" >> $GITHUB_ENV
          echo "DB_USER=$(gcloud secrets versions access latest --secret=DB_USER)" >> $GITHUB_ENV
          echo "DB_PASSWORD=$(gcloud secrets versions access latest --secret=DB_PASSWORD)" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hytteportalen \
            --image=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/spkhytta/spkhytta \
            --platform=managed \
            --region=${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --add-cloudsql-instances=spkhytta:europe-west1:spkhytta-db \
            --set-env-vars=DB_URL=${{ env.DB_URL }},DB_USER=${{ env.DB_USER }},DB_PASSWORD=${{ env.DB_PASSWORD }}
      
